added validation for ssh creds

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -110,6 +110,12 @@ runs:
           exit 1
         fi
 
+        # Checking credentials
+        if ! ssh -i "$TEMP_KEY_FILE" -o StrictHostKeyChecking=no -o BatchMode=yes "$SSH_USER@$SSH_HOST" "exit" 2>/dev/null; then
+          echo "Error: SSH authentication failed. Please check your SSH credentials."
+          exit 1
+        fi
+
         if [[ "$WP_DEST_DIR" != "$WP_ROOT_DIR" ]]; then
           if ! ssh -i "$TEMP_KEY_FILE" -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" "[ -d '/$WP_DEST_DIR' ]"; then
             echo "Error: Directory '/$WP_DEST_DIR' does not exist on the server."
